---
# MySQL Configuration Tasks
- include_vars: secrets.yml
- name: Ensure Presence of MySQL and Required Dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  loop:
    - python3-pip
    - mysql-server
    - mysql-client
  tags: [ packages, mysql ]

- name: Install PyMySQL Python Package
  ansible.builtin.pip:
    name: pymysql==1.1.0


- name: Enable MySQL Service for Startup
  service:
    name: mysql
    state: started
    enabled: true
  notify:
    - restart mysql



- name: Set Up MySQL Database
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    login_host: "{{ db_host }}"
    login_port: "{{ login_port }}"
  tags: [ mysql ]



...